import { Channel, ChannelPost, ChannelComment } from '@/types/database';

export const INITIAL_CHANNELS: Channel[] = [
  {
    id: 'ch-gaming',
    name: 'Gaming Continuum',
    slug: 'gaming',
    description: 'A nexus for gaming discussions, patch reviews, hidden mechanics, build showcases, and deep-dive lore.',
    category: 'Gaming',
    avatar_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
    member_count: 14200,
    weekly_visitors: 4820,
    weekly_contributions: 312,
    rules: [
      'Remember the human & remain respectful.',
      'Mark all story spoilers clearly with spoiler tags.',
      'No low-effort self-promotion without context.',
      'Constructive debate only on reviews and ratings.',
    ],
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'ch-anime',
    name: 'Anime & Manga Sphere',
    slug: 'anime',
    description: 'Weekly seasonal anime episodes, manga chapter reactions, studio animation breakdowns, and sound design talks.',
    category: 'Anime',
    avatar_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    member_count: 9800,
    weekly_visitors: 3200,
    weekly_contributions: 189,
    rules: [
      'Untranslated raws must be tagged.',
      'Credit all artists and animators.',
      'Strict spoiler warnings for ongoing manga arcs.',
    ],
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'ch-movies',
    name: 'Cinema & Pop Culture',
    slug: 'cinema',
    description: 'Director commentaries, cinematography critiques, film score appreciation, and pop culture analysis.',
    category: 'Pop Culture',
    avatar_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1200&auto=format&fit=crop&q=80',
    member_count: 6500,
    weekly_visitors: 1940,
    weekly_contributions: 94,
    rules: [
      'Original reviews and essays welcomed.',
      'Respect differing artistic opinions.',
    ],
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'ch-tech',
    name: 'Hardware & Tech Lab',
    slug: 'tech',
    description: 'GPU benchmarks, OLED displays, custom mechanical keyboards, and next-gen gaming hardware setups.',
    category: 'Tech',
    avatar_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80',
    member_count: 5100,
    weekly_visitors: 1200,
    weekly_contributions: 64,
    rules: [
      'Post verified benchmarks where possible.',
      'No piracy or cracked software discussion.',
    ],
    created_at: '2024-04-05T00:00:00Z',
  }
];

export const INITIAL_POSTS: ChannelPost[] = [
  {
    id: 'post-1',
    channel_id: 'ch-gaming',
    user_id: 'user-elena',
    author_name: 'Elena Rostova',
    author_username: 'elena_cyber',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena_cyber',
    author_badges: ['top_1_percent_commenter', 'top_5_percent_poster'],
    title: 'Shadow of the Erdtree: Why Messmer is FromSoft\'s most mathematically tuned boss yet',
    content: 'Greetings, after 60+ hours of frame-data analysis and hit-box testing on NG+7, I wanted to open a deep discussion on how Messmer the Impaler bridges the gap between classic Bloodborne aggression and Elden Ring\'s complex delayed tracking.\n\nNotice how the second phase serpent strikes don\'t actually track during startup—they lock on at frame 14, giving you a precise 6-frame window for i-frame rolling forward rather than sideways.\n\nWhat are your thoughts on this encounter compared to Malenia or Isshin?',
    flair: 'Deep Analysis',
    media_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1000&auto=format&fit=crop&q=80',
    upvotes: 342,
    downvotes: 18,
    comments_count: 28,
    is_pinned: true,
    created_at: '4 hours ago',
  },
  {
    id: 'post-2',
    channel_id: 'ch-gaming',
    user_id: 'user-viktor',
    author_name: 'Viktor Vance',
    author_username: 'viktor_v',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=viktor_v',
    author_badges: ['verified_critic'],
    title: 'The state of Unreal Engine 5 stutter in 2026: Shader compilation compilation analysis',
    content: 'We tested 12 recent UE5 titles on both high-end RTX 4090 and mid-range hardware. PSO caching has definitely improved with 5.4, but traversal hitches persist due to aggressive asset streaming. Are developers relying too much on DLSS/FSR rather than raw pipeline tuning?',
    flair: 'Tech Breakdown',
    upvotes: 189,
    downvotes: 7,
    comments_count: 14,
    created_at: '8 hours ago',
  },
  {
    id: 'post-3',
    channel_id: 'ch-anime',
    user_id: 'user-kenji',
    author_name: 'Kenji Takahashi',
    author_username: 'kenji_sensei',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kenji_sensei',
    author_badges: ['top_1_percent_commenter'],
    title: 'Frieren: Beyond Journey\'s End and the poetic mastery of silent storytelling',
    content: 'Episode 28 demonstrated how silence, micro-expressions, and atmospheric sound design evoke tenfold more emotion than lengthy internal monologues. Studio Madhouse set an unprecedented standard here.',
    flair: 'Discussion',
    media_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1000&auto=format&fit=crop&q=80',
    upvotes: 512,
    downvotes: 11,
    comments_count: 42,
    created_at: '1 day ago',
  },
  {
    id: 'post-4',
    channel_id: 'ch-movies',
    user_id: 'user-clara',
    author_name: 'Clara Oswald',
    author_username: 'clara_films',
    author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=clara_films',
    author_badges: ['top_5_percent_poster'],
    title: 'Dune Part Two: How Greig Fraser redefined modern desert cinematography using infrared',
    content: 'The Giedi Prime arena sequences shot in pure Infrared spectrum stripped away the standard Hollywood CGI look and replaced it with a haunting, otherworldly starkness.',
    flair: 'Cinematography',
    upvotes: 245,
    downvotes: 5,
    comments_count: 19,
    created_at: '2 days ago',
  }
];

export const INITIAL_COMMENTS: Record<string, ChannelComment[]> = {
  'post-1': [
    {
      id: 'comm-mod-1',
      post_id: 'post-1',
      parent_id: null,
      user_id: 'mod-auto',
      author_name: 'AutoModerator',
      author_username: 'AutoModerator',
      author_avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=AutoMod',
      author_badges: ['moderator'],
      content: 'Welcome to r/gaming! Please ensure all comments follow our community standards. Keep discussions constructive, respect diverse playstyles, and tag late-game DLC boss spoilers.',
      upvotes: 95,
      downvotes: 2,
      is_mod: true,
      is_pinned: true,
      created_at: '4h ago',
      replies: [],
    },
    {
      id: 'comm-1',
      post_id: 'post-1',
      parent_id: null,
      user_id: 'user-express',
      author_name: 'Express Sky',
      author_username: 'Express_Sky0091',
      author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Express_Sky0091',
      author_badges: ['top_1_percent_commenter'],
      content: 'Completely agree on the frame 14 lock-in. When I was running a Light Load dagger build, rolling forward into his spear thrust gave me enough recovery frames to land a full heavy charge. The cadence feels like a fast-paced waltz once you stop dodging backwards.',
      upvotes: 108,
      downvotes: 4,
      created_at: '4h ago',
      replies: [
        {
          id: 'comm-1-1',
          post_id: 'post-1',
          parent_id: 'comm-1',
          user_id: 'user-pupul',
          author_name: 'Pupul Here',
          author_username: 'pupul-here',
          author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pupul-here',
          author_badges: [],
          content: 'This! Most players complain about the camera or the serpent hitboxes simply because they instinctively panic-roll backwards away from his fire trails.',
          upvotes: 51,
          downvotes: 2,
          created_at: '4h ago',
          replies: [
            {
              id: 'comm-1-1-1',
              post_id: 'post-1',
              parent_id: 'comm-1-1',
              user_id: 'user-elena',
              author_name: 'Elena Rostova',
              author_username: 'elena_cyber',
              author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena_cyber',
              author_badges: ['top_1_percent_commenter', 'original_poster'],
              content: 'Spot on @pupul-here. The arena geometry was purposefully designed flat so you wouldn\'t snag on debris while positioning under the wing sweep.',
              upvotes: 42,
              downvotes: 0,
              is_op: true,
              created_at: '3h ago',
              replies: [],
            }
          ]
        },
        {
          id: 'comm-1-2',
          post_id: 'post-1',
          parent_id: 'comm-1',
          user_id: 'user-aalok',
          author_name: 'Aalok Paratha',
          author_username: 'Aalokaparatha',
          author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aalokaparatha',
          author_badges: ['top_1_percent_commenter'],
          content: 'aww thats so accurate... my strength build was getting flattened until I swapped to Deflecting Hardtear and guarded the initial thrust.',
          upvotes: 123,
          downvotes: 3,
          created_at: '4h ago',
          replies: [
            {
              id: 'comm-1-2-1',
              post_id: 'post-1',
              parent_id: 'comm-1-2',
              user_id: 'user-euphoric',
              author_name: 'Euphoric Record',
              author_username: 'Euphoric-Record816',
              author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Euphoric-Record816',
              author_badges: ['top_1_percent_commenter'],
              content: 'Deflecting Hardtear is basically Sekiro mode unlocked in Elden Ring. Best addition in the entire DLC! 😂🔥',
              upvotes: 86,
              downvotes: 1,
              created_at: '4h ago',
              replies: []
            }
          ]
        }
      ]
    },
    {
      id: 'comm-2',
      post_id: 'post-1',
      parent_id: null,
      user_id: 'user-marcus',
      author_name: 'Marcus Cole',
      author_username: 'marcus_c',
      author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus_c',
      author_badges: ['top_5_percent_poster'],
      content: 'Can we also talk about the lore integration? The soundtrack during phase 2 seamlessly brings in the Marika motif in a minor key.',
      upvotes: 74,
      downvotes: 1,
      created_at: '2h ago',
      replies: []
    }
  ]
};
