import { MediaTitle } from '@/types/media';

export const INITIAL_MEDIA_TITLES: MediaTitle[] = [
  {
    id: 'daayra',
    slug: 'daayra',
    title: 'Daayra',
    type: 'movie',
    badge: 'Trailer',
    releaseYear: 2026,
    releaseDate: 'October 2026',
    status: 'In Production / Upcoming',
    genres: ['Thriller', 'Crime', 'Drama', 'Mystery'],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ', // Can be any youtube ID
    rating: 8.8,
    directorOrDev: 'Meghna Gulzar',
    studio: 'Junglee Pictures',
    country: 'India',
    language: 'Hindi',
    durationOrPlatforms: '2h 18m',
    overview: 'Daayra is an upcoming Indian Hindi-language investigative thriller film written and directed by Meghna Gulzar. The film stars Kareena Kapoor Khan and Prithviraj Sukumaran in the lead roles as police officers navigating a harrowing, high-stakes moral labyrinth.',
    interestedCount: 1420,
    collectionCount: 184,
    cast: [
      { name: 'Kareena Kapoor Khan', role: 'SP Nandita Rao', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80' },
      { name: 'Prithviraj Sukumaran', role: 'ACP Kabir Dev', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80' },
      { name: 'Meghna Gulzar', role: 'Director & Co-Writer', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80' },
    ],
    relatedArticles: [
      {
        id: 'daayra-first-look-breakdown',
        title: 'Daayra Teaser Breakdown: Meghna Gulzar Returns to High-Tension Crime Cinema',
        slug: 'daayra-first-look-breakdown',
        category: 'Analysis',
        readTime: '4 min read',
        author: 'Arjun Verma',
        publishedAt: '2 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&q=80',
      },
      {
        id: 'daayra-prithviraj-role',
        title: 'Why Prithviraj Sukumaran & Kareena Kapoor is Bollywood’s Most Intriguing Pairing of 2026',
        slug: 'daayra-prithviraj-role',
        category: 'Editorial',
        readTime: '6 min read',
        author: 'Ria Sengupta',
        publishedAt: '1 week ago',
        thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
      },
    ],
    tags: ['Investigative', 'Police Procedural', 'Crime', '2026 Anticipated'],
  },
  {
    id: 'toxic-fairy-tale',
    slug: 'toxic-fairy-tale',
    title: 'Toxic: A Fairy Tale for Grown-ups',
    type: 'movie',
    badge: 'New Movie',
    releaseYear: 2026,
    releaseDate: 'April 10, 2026',
    status: 'Post-Production',
    genres: ['Action', 'Thriller', 'Noir', 'Crime'],
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.5,
    directorOrDev: 'Geetu Mohandas',
    studio: 'KVN Productions / Monster Mind',
    country: 'India',
    language: 'Kannada / Multi-Lingual',
    durationOrPlatforms: '2h 35m',
    overview: 'Yash stars in Geetu Mohandas’s gritty, hyper-stylized noir thriller delving deep into an underground underworld drug empire and redemption saga set across 1960s to 1980s coastal drug trade routes.',
    interestedCount: 3890,
    collectionCount: 520,
    cast: [
      { name: 'Yash', role: 'Raya / The Boss', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80' },
      { name: 'Kiara Advani', role: 'Lead Female', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80' },
      { name: 'Nayanthara', role: 'Special Appearance', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80' },
    ],
    relatedArticles: [
      {
        id: 'toxic-yash-transformation',
        title: 'Deconstructing Yash’s Grim Transformation for Toxic: The Fairy Tale Gone Rogue',
        slug: 'toxic-yash-transformation',
        category: 'Deep Dive',
        readTime: '7 min read',
        author: 'Karan Mehra',
        publishedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
      },
    ],
    tags: ['Yash', 'High-Octane Noir', 'Action'],
  },
  {
    id: 'lanterns',
    slug: 'lanterns',
    title: 'Lanterns',
    type: 'tv',
    badge: 'Season 1 Episode 3',
    releaseYear: 2026,
    releaseDate: 'Summer 2026',
    status: 'Air Weekly',
    genres: ['Sci-Fi', 'Mystery', 'Detective', 'Superhero'],
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.1,
    directorOrDev: 'Chris Mundy / Damon Lindelof',
    studio: 'HBO / DC Studios',
    country: 'United States',
    language: 'English',
    durationOrPlatforms: '8 Episodes • HBO Max',
    overview: 'Two intergalactic cops—legend Hal Jordan and rookie John Stewart—are drawn into a dark, Earth-based mystery as they investigate an ancient terrestrial murder with cosmic ramifications.',
    interestedCount: 2940,
    collectionCount: 310,
    cast: [
      { name: 'Kyle Chandler', role: 'Hal Jordan', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80' },
      { name: 'Aaron Pierre', role: 'John Stewart', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80' },
    ],
    relatedArticles: [
      {
        id: 'lanterns-true-detective-vibe',
        title: 'Why HBO’s Lanterns is Channeling True Detective Rather than Classic Comic Fare',
        slug: 'lanterns-true-detective-vibe',
        category: 'TV Review',
        score: '9.4',
        readTime: '5 min read',
        author: 'Elena Rostova',
        publishedAt: 'Yesterday',
        thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&q=80',
      },
    ],
    tags: ['DCU', 'True Detective', 'Cosmic Noir'],
  },
  {
    id: 'gta-vi',
    slug: 'gta-vi',
    title: 'Grand Theft Auto VI',
    type: 'game',
    badge: 'OTT Release',
    releaseYear: 2026,
    releaseDate: 'Fall 2026',
    status: 'Anticipated Release',
    genres: ['Open World', 'Action', 'Crime', 'Sandbox'],
    posterUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.9,
    directorOrDev: 'Rockstar Games',
    studio: 'Take-Two Interactive',
    country: 'United States',
    language: 'English',
    durationOrPlatforms: 'PlayStation 5, Xbox Series X/S',
    overview: 'Grand Theft Auto VI heads to the state of Leonida, home to the neon-soaked streets of Vice City and beyond, in the biggest, most immersive evolution of the Grand Theft Auto series yet.',
    interestedCount: 15400,
    collectionCount: 3400,
    cast: [
      { name: 'Lucia', role: 'Protagonist', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80' },
      { name: 'Jason', role: 'Protagonist', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80' },
    ],
    relatedArticles: [
      {
        id: 'gta-vi-physics-ai-breakdown',
        title: 'The AI & Physics Revolution Behind GTA VI’s Living, Breathing Vice City',
        slug: 'gta-vi-physics-ai-breakdown',
        category: 'Tech & Gaming',
        score: '10/10',
        readTime: '10 min read',
        author: 'Adrian Vance',
        publishedAt: '4 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&q=80',
      },
    ],
    tags: ['Vice City', 'Rockstar', 'Next-Gen Open World'],
  },
  {
    id: 'batman-knightfall',
    slug: 'batman-knightfall',
    title: 'Batman: Knightfall Part 1',
    type: 'movie',
    badge: 'New Movie',
    releaseYear: 2026,
    releaseDate: 'Late 2026',
    status: 'Official Animated Feature',
    genres: ['Animation', 'Action', 'Superhero', 'Dark Fantasy'],
    posterUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.3,
    directorOrDev: 'DC Animation / Warner Bros.',
    studio: 'Warner Bros. Animation',
    country: 'United States',
    language: 'English',
    durationOrPlatforms: '1h 48m',
    overview: 'The definitive two-part animated adaptation of DC’s iconic 1993 storyline. Bane stages a mass breakout at Arkham Asylum to exhaust the Dark Knight before breaking him both physically and psychologically.',
    interestedCount: 2210,
    collectionCount: 410,
    relatedArticles: [
      {
        id: 'knightfall-comic-vs-film',
        title: 'Knightfall Adaptation: Faithfulness to 90s Chuck Dixon Comic vs Modern Reimagining',
        slug: 'knightfall-comic-vs-film',
        category: 'Comic Critique',
        readTime: '5 min read',
        author: 'Marcus Chen',
        publishedAt: '5 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&q=80',
      },
    ],
    tags: ['Bane', 'Batman', 'DC Animation', 'Knightfall'],
  },
  {
    id: 'indias-got-latent',
    slug: 'indias-got-latent',
    title: "India's Got Latent",
    type: 'tv',
    badge: 'New Episode',
    releaseYear: 2026,
    releaseDate: 'Weekly',
    status: 'Streaming',
    genres: ['Comedy', 'Reality', 'Talk Show', 'Unscripted'],
    posterUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.0,
    directorOrDev: 'Samay Raina Production',
    studio: 'Independent / YouTube / Netflix',
    country: 'India',
    language: 'Hindi / English',
    durationOrPlatforms: 'Episodes ~50m',
    overview: 'A viral subversive talent format where ordinary participants demonstrate obscure, odd, or accidental latent skills in front of unpredictable celebrity comic panels.',
    interestedCount: 6800,
    collectionCount: 920,
    tags: ['Comedy', 'Standup', 'Viral'],
  },
  {
    id: 'the-whisper-man',
    slug: 'the-whisper-man',
    title: 'The Whisper Man',
    type: 'movie',
    badge: 'New Movie',
    releaseYear: 2026,
    releaseDate: 'November 2026',
    status: 'Post-Production',
    genres: ['Horror', 'Psychological Thriller', 'Mystery'],
    posterUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 8.6,
    directorOrDev: 'Robert Eggers',
    studio: 'A24',
    country: 'United States',
    language: 'English',
    durationOrPlatforms: '2h 05m',
    overview: 'In a quiet English village, a widower and his young son find themselves haunted by terrifying whispers at their bedroom window that match the chilling modus operandi of an executed serial killer.',
    interestedCount: 1870,
    collectionCount: 240,
    tags: ['Psychological Horror', 'A24', 'Supernatural'],
  },
  {
    id: 'the-dog-stars',
    slug: 'the-dog-stars',
    title: 'The Dog Stars',
    type: 'movie',
    badge: 'New Movie',
    releaseYear: 2026,
    releaseDate: 'Winter 2026',
    status: 'Filming',
    genres: ['Sci-Fi', 'Post-Apocalyptic', 'Drama', 'Survival'],
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 8.9,
    directorOrDev: 'Ridley Scott',
    studio: '20th Century Studios',
    country: 'United States',
    language: 'English',
    durationOrPlatforms: '2h 20m',
    overview: 'Based on Peter Heller’s celebrated post-pandemic novel, a pilot lives in an abandoned Colorado hangar with his dog and a paranoid ex-marine. When a faint radio signal crackles over his Cessna’s headset, he flies beyond his perimeter of safety.',
    interestedCount: 1980,
    collectionCount: 310,
    tags: ['Survival', 'Sci-Fi', 'Ridley Scott'],
  },
  {
    id: 'hanuman-ansh',
    slug: 'hanuman-ansh',
    title: 'Hanuman Ansh',
    type: 'movie',
    badge: 'New Movie',
    releaseYear: 2026,
    releaseDate: 'Diwali 2026',
    status: 'Production',
    genres: ['Mythology', 'Fantasy', 'Action', 'Adventure'],
    posterUrl: 'https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.3,
    directorOrDev: 'Prasanth Varma',
    studio: 'Prasanth Varma Cinematic Universe (PVCU)',
    country: 'India',
    language: 'Telugu / Multi-Lingual',
    durationOrPlatforms: '2h 40m',
    overview: 'Continuing the expanding Indian mythical superhero universe, Hanuman Ansh follows the awakening of dormant ancient cosmic energy in modern-day Himalayas against primordial dark entities.',
    interestedCount: 4200,
    collectionCount: 780,
    tags: ['PVCU', 'Mythology', 'Indian Superhero'],
  },
  {
    id: 'bandar',
    slug: 'bandar',
    title: 'Bandar',
    type: 'movie',
    badge: 'OTT Release',
    releaseYear: 2026,
    releaseDate: 'Streaming Now',
    status: 'Released',
    genres: ['Comedy', 'Crime', 'Satire', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 8.4,
    directorOrDev: 'Anurag Kashyap',
    studio: 'Good Bad Films',
    country: 'India',
    language: 'Hindi',
    durationOrPlatforms: '1h 55m',
    overview: 'A sharp, dark situational comedy revolving around a chaotic small-town election that spirals out of control after a stolen monkey becomes the unlikely symbol of political resistance.',
    interestedCount: 1620,
    collectionCount: 220,
    tags: ['Satire', 'Dark Comedy', 'Crime'],
  },
  {
    id: 'demon-slayer-infinity-castle',
    slug: 'demon-slayer-infinity-castle',
    title: 'Demon Slayer: Infinity Castle Movie Trilogy',
    type: 'anime',
    badge: 'Trailer',
    releaseYear: 2026,
    releaseDate: 'Late 2026',
    status: 'Upcoming Theatrical',
    genres: ['Anime', 'Shonen', 'Dark Fantasy', 'Action'],
    posterUrl: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.8,
    directorOrDev: 'Haruo Sotozaki / Ufotable',
    studio: 'Ufotable',
    country: 'Japan',
    language: 'Japanese',
    durationOrPlatforms: 'Theatrical Trilogy • Worldwide Release',
    overview: 'The Hashira and the Demon Slayer Corps infiltrate the non-Euclidean shifting dimensions of Muzan Kibutsuji’s Infinity Castle for the final, bloody showdown against the Upper Rank demons.',
    interestedCount: 11200,
    collectionCount: 2800,
    relatedArticles: [
      {
        id: 'infinity-castle-cgi-breakdown',
        title: 'How Ufotable Leveraged Unreal Engine 5 Hybrid Shading for the Infinity Castle Dimension',
        slug: 'infinity-castle-cgi-breakdown',
        category: 'Anime Tech',
        score: '9.9',
        readTime: '6 min read',
        author: 'Kenji Tanaka',
        publishedAt: '3 days ago',
        thumbnail: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=600&q=80',
      },
    ],
    tags: ['Demon Slayer', 'Ufotable', 'Shonen Peak'],
  },
  {
    id: 'elden-ring-shadow-erdtree',
    slug: 'elden-ring-shadow-erdtree',
    title: 'Elden Ring: Shadow of the Erdtree',
    type: 'game',
    badge: 'Must Play',
    releaseYear: 2024,
    releaseDate: 'Available Now',
    status: 'Masterpiece',
    genres: ['Action RPG', 'Soulsborne', 'Dark Fantasy', 'Open World'],
    posterUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=85',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
    trailerYoutubeId: 'dQw4w9WgXcQ',
    rating: 9.8,
    directorOrDev: 'Hidetaka Miyazaki',
    studio: 'FromSoftware / Bandai Namco',
    country: 'Japan',
    language: 'English / Multi',
    durationOrPlatforms: 'PC, PS5, PS4, Xbox Series X/S, Xbox One',
    overview: 'Guided by Empyrean Miquella, players step into the Realm of Shadow, a land obscured by the Erdtree where goddess Marika first set foot, to unravel dark buried secrets of divinity and decay.',
    interestedCount: 18900,
    collectionCount: 4200,
    relatedArticles: [
      {
        id: 'elden-ring-shadow-erdtree-review',
        title: 'Elden Ring: Shadow of the Erdtree — The Definitive Verdict',
        slug: 'elden-ring-shadow-erdtree-review',
        category: 'Game Review',
        score: '9.8',
        readTime: '12 min read',
        author: 'Adrian Vance',
        publishedAt: 'August 24, 2026',
        thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=85',
      },
    ],
    tags: ['FromSoftware', 'Miyazaki', 'Soulsborne'],
  },
];

// In-memory / localStorage reactive store helper so we don't blow memory
export function getMediaCatalog(): MediaTitle[] {
  if (typeof window !== 'undefined') {
    const custom = localStorage.getItem('infinity_custom_media');
    if (custom) {
      try {
        const parsed = JSON.parse(custom);
        return [...parsed, ...INITIAL_MEDIA_TITLES];
      } catch (e) {
        console.error('Failed to parse custom media', e);
      }
    }
  }
  return INITIAL_MEDIA_TITLES;
}

export function getMediaById(idOrSlug: string): MediaTitle | undefined {
  const all = getMediaCatalog();
  return all.find((m) => m.id === idOrSlug || m.slug === idOrSlug);
}

export function getMediaByGenre(genre: string): MediaTitle[] {
  const all = getMediaCatalog();
  if (!genre || genre.toLowerCase() === 'all') return all;
  return all.filter((m) =>
    m.genres.some((g) => g.toLowerCase() === genre.toLowerCase()) ||
    m.type.toLowerCase() === genre.toLowerCase()
  );
}
